CREATE TABLE policial
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(100) NOT NULL,
    cpf        VARCHAR(14) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    nascimento TIMESTAMP NOT NULL,
    nome_mae   VARCHAR(255),
    nome_pai   VARCHAR(255),
    ativo      BOOLEAN DEFAULT TRUE,
    CONSTRAINT pk_policial PRIMARY KEY (id)
);