CREATE TABLE policial
(
    id                BIGINT NOT NULL auto_increment,
    nome              VARCHAR(100) NOT NULL ,
    cpf               VARCHAR(15) NOT NULL UNIQUE ,
    email             VARCHAR(100) NOT NULL UNIQUE ,
    nascimento        TIMESTAMP,
    nome_mae          VARCHAR(100),
    nome_pai          VARCHAR(100),
    patente           VARCHAR(10) NOT NULL ,
    nome_de_guerra    VARCHAR(30) NOT NULL ,
    lotacao           VARCHAR(30) NOT NULL ,
    matricula         INTEGER NOT NULL UNIQUE ,
    data_incorporacao TIMESTAMP NOT NULL ,
    ativo             BOOLEAN NOT NULL,
    grau              VARCHAR(30),
    curso             VARCHAR(30),
    concluido         BOOLEAN,
    ano_conclusao     INTEGER,
    logradouro        VARCHAR(40) NOT NULL ,
    numero            VARCHAR(10),
    complemento       VARCHAR(40),
    bairro            VARCHAR(40) NOT NULL ,
    cidade            VARCHAR(40) NOT NULL ,
    uf                VARCHAR(2) NOT NULL ,
    cep               VARCHAR(10) NOT NULL ,
    PRIMARY KEY (id)
);